### ISSUE TITLE
Running make on RHEL results in an error.  

### ISSUE THREAD

**Issue by DrLynch** [ETS-Next-Gen/writing_observer#10]
Following existing instructions to run make I get the following error:

(learning_observer) [cflynch@lin-res07 writing_observer]$ sudo make
# If you haven't done so yet, run: make install
# Also, run: workon learning_observer
cd learning_observer && python learning_observer
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/share/Projects/WritingObserver/Repo/writing_observer/learning_observer/learning_observer/__main__.py", line 7, in <module>
    import learning_observer.main as main
ImportError: No module named learning_observer.main
make: *** [run] Error 1

**Comment by DrLynch** [comment]
This is nor resolved.  The issue was due to permission problems on the server.  I am keeping running noites of RHEL specific changes.
