### ISSUE TITLE
Set extension access security for non-Chrome logins.

### ISSUE THREAD

**Issue by DrLynch** [ETS-Next-Gen/writing_observer#15]
The current security model for the extension assumes that the student is logged into both a google account linked to the class and logged into Chrome with the same account.  While this is the norm for chrome users it is not for other platforms.  Ergo we will need to consider another security model down the road.

**Comment by DrLynch** [comment]
As additional info, on the server side this triggers a recoverable error:

Error handling request
Traceback (most recent call last):
  File "/usr/local/share/Projects/WritingObserver/VirtualENVs/learning_observer/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/share/Projects/WritingObserver/VirtualENVs/learning_observer/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/share/Projects/WritingObserver/VirtualENVs/learning_observer/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/local/share/Projects/WritingObserver/VirtualENVs/learning_observer/lib/python3.8/site-packages/aiohttp_session/__init__.py", line 154, in factory
    response = await handler(request)
  File "/usr/local/share/Projects/WritingObserver/Repo-Fork/writing_observer/learning_observer/learning_observer/auth/handlers.py", line 55, in auth_middleware
    resp = await handler(request)
  File "/usr/local/share/Projects/WritingObserver/Repo-Fork/writing_observer/learning_observer/learning_observer/incoming_student_event.py", line 283, in incoming_websocket_handler
    event_metadata['auth'] = await learning_observer.auth.events.authenticate(
  File "/usr/local/share/Projects/WritingObserver/Repo-Fork/writing_observer/learning_observer/learning_observer/auth/events.py", line 296, in authenticate
    auth_metadata = await AUTH_METHODS[auth_method](request, headers, first_event, source)
  File "/usr/local/share/Projects/WritingObserver/Repo-Fork/writing_observer/learning_observer/learning_observer/auth/events.py", line 207, in chromebook_auth
    gc_uid = learning_observer.auth.utils.google_id_to_user_id(untrusted_google_id)
  File "/usr/local/share/Projects/WritingObserver/Repo-Fork/writing_observer/learning_observer/learning_observer/auth/utils.py", line 35, in google_id_to_user_id
    return "gc-" + str(int(google_id))
ValueError: invalid literal for int() with base 10: ''

**Comment by bradley-erickson** [comment]
Related to #2

**Comment by DrLynch** [comment]
Given our current use case we can pause this for the time being.
