### ISSUE TITLE
OS Error triggered by open file connections in sockets.

### ISSUE THREAD

**Issue by DrLynch** [ETS-Next-Gen/writing_observer#17]
It appears that the existing codebase leaks open file sockets.  After some period of execution it triggers an error for number of open files.  This appears to be time not activity related as it was triggered after a long period when no activity had taken place.  

Relevant log error:
Error handling request
Traceback (most recent call last):
  File "/usr/local/share/Projects/WritingObserver/VirtualENVs/learning_observer/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/share/Projects/WritingObserver/VirtualENVs/learning_observer/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/share/Projects/WritingObserver/VirtualENVs/learning_observer/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/local/share/Projects/WritingObserver/VirtualENVs/learning_observer/lib/python3.8/site-packages/aiohttp_session/__init__.py", line 154, in factory
    response = await handler(request)
  File "/usr/local/share/Projects/WritingObserver/Repo-Fork/writing_observer/learning_observer/learning_observer/auth/handlers.py", line 55, in auth_middleware
    resp = await handler(request)
  File "/usr/local/share/Projects/WritingObserver/Repo-Fork/writing_observer/learning_observer/learning_observer/incoming_student_event.py", line 275, in incoming_websocket_handler
    debug_log("Web socket message received")
  File "/usr/local/share/Projects/WritingObserver/Repo-Fork/writing_observer/learning_observer/learning_observer/log_event.py", line 197, in debug_log
    debug_fp = open(paths.logs("debug.log"), "a")
OSError: [Errno 24] Too many open files: '/usr/local/share/Projects/WritingObserver/Repo-Fork/writing_observer/learning_observer/learning_observer/logs/debug.log'
socket.accept() out of system resource
socket: <asyncio.TransportSocket fd=7, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=6, laddr=('::', 8888, 0, 0)>
Traceback (most recent call last):
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/asyncio/selector_events.py", line 164, in _accept_connection
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
socket.accept() out of system resource
socket: <asyncio.TransportSocket fd=7, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=6, laddr=('::', 8888, 0, 0)>
Traceback (most recent call last):
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/asyncio/selector_events.py", line 164, in _accept_connection
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
socket.accept() out of system resource
socket: <asyncio.TransportSocket fd=7, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=6, laddr=('::', 8888, 0, 0)>
Traceback (most recent call last):
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/asyncio/selector_events.py", line 164, in _accept_connection
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/socket.py", line 292, in accept

**Comment by DrLynch** [comment]
It appears the source of this error lies in incoming_student_event under incoming_websocket_handler where it triggers a new log to be created on each new websocket.  This has been happening intermittently until now but it raises an issue of scalability.

**Comment by DrLynch** [comment]
The open question is, do these need to be in a separate file or can they be stored in the pubsub.
