### ISSUE TITLE
Request Handling error.

### ISSUE THREAD

**Issue by DrLynch** [ETS-Next-Gen/writing_observer#19]
Arises after runtime, unclear trigger.

Error handling request
Traceback (most recent call last):
  File "/usr/local/share/Projects/WritingObserver/VirtualENVs/learning_observer/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 314, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 546, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'invalid HTTP method'"

**Comment by DrLynch** [comment]
This has been addressed.  It was due to an issue with the login code.
